### ISSUE TITLE
Dose response

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#11]
The dose response curves for chemicals in this study were done before DB 3.0 was incorporated. We need to update those and I can take another look--especially for the chemicals that are showing up as a priority.

**Comment by ldecicco-USGS** [comment]
We did generate them this summer. I don't remember where on the Projects drive I put it, but the graphs I made I copied over to here:
https://doimspp-my.sharepoint.com/personal/srcorsi_usgs_gov/_layouts/15/onedrive.aspx?id=%2fpersonal%2fsrcorsi_usgs_gov%2fDocuments%2fGLRI+CECs%2fPhase+I%2fPassive%2fManuscript%2fFigures%2fdoseV3&FolderCTID=0x012000A09D88CFE962D44B98344DAF211A723D

I've got a script ready to re-generate the curves by chemical, but the virtual machine's memory seems to be insufficient (I think this is a new issue). I made an IT ticket, and it sounds like they'll get that sorted out soon. When that's done, I'll push the pdfs by chemical (sorted by max EAR) up on that sharepoint folder.

**Comment by srcorsi-USGS** [comment]
D-Limonene pdf is empty. I looked at Comptox, and it has three active endpoints, two of which I would exclude:
TOX21_RT_HEK293_FLO_32hr_viability
TOX21_RT_HEK293_FLO_40hr_viability

Both have flags for overfitting and only one concentration above baseline (we don't exclude automatically based on these two flags).

the third endpoint dose response (ATG_PXRE_CIS_up) looks legit.

**Comment by srcorsi-USGS** [comment]
I have added those exclusions into the exclude spreadsheet on onedrive here: GLRI CECs\Phase I\Passive\Manuscript\data\data_for_git_repo\raw
