### ISSUE TITLE
Pathways table revision

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#12]
To facilitate analysis and writing in the results section, generate another table that includes one row per AOP (so multiple rows per endpoint in some instances) and add entries from the AOP title column (in the AOP mapping). This will provide info for filling out AOP descriptive text and developing AOP short names.
 
Then, generate a df with the expanded AOP info that Dan provided in the ecological relevance table. I have placed that table in the "raw" directory. Add two more columns to the above table: Eco relevance  (Yes, No, Maybe), and rationale. For those endpoints with no AOPs, retain them for Dan to take another look at potential associations.

**Comment by ldecicco-USGS** [comment]
Still debating the best way to do this...but, I added a table:

```r
library(tidyverse)
AOP_info <- readxl::read_xlsx("data/supplemental/SI_6_AOP_relevance With Short AOP name.xlsx", 
                              sheet = "SI_AOP_relevance") %>% 
  group_by(AOP, Relevant, Rationale, `...5`) %>% 
  summarize(`EndPoint(s)` = paste0(`Endpoint(s)`, collapse = ", ")) %>% 
  rename(`Abbreviated AOP description` = `...5`) %>% 
  ungroup()
```

In our OneDrive Manuscript folder, there's a "data" folder. I added a new subfolder "data_for_git_repo"....within that folder is the data needed to run any of our scripts (including this). So, that "SI_6_AOP_relevance With Short AOP name" file is in there.

**Comment by srcorsi-USGS** [comment]
1. Switch from AOP ID to shortname. shortnames have been added to AOP crosswalk for AOPs that are included in this study.
2. Change chem names in table to abbreviations to be consistent with text:
4-(1,1,3,3-Tetramethylbutyl)phenol -> p-tert-Octylphenol, 
Tris(2-chloroisopropyl)phosphate -> TCPP 
Tris(2-butoxyethyl) phosphate -> TBEP
Tris(1,3-dichloro-2-propyl) phosphate  -> TDCPP
diethylhexylpthalate -> DEHP

**Comment by ldecicco-USGS** [comment]
"in table" meaning the "AOP_info" above, or the mixtures table?

**Comment by ldecicco-USGS** [comment]
"shortnames have been added to AOP crosswalk"...what file did you add this to?

**Comment by srcorsi-USGS** [comment]
AOP_crosswalk.csv in data/raw directory. Maybe that doesn't get pushed to the repo... I just copied it into the data/raw directory on onedrive.

**Comment by ldecicco-USGS** [comment]
I've got #1 done above if you want to do an upstream pull. I'll switch the chemical names next.
