### ISSUE TITLE
Stack by site SI for individual chem classes

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#14]
Add figure captions:
Figure SI-xx-XX. Maximum exposure-activity ratios (EAR) for [ADD CHEMICAL CLASS NAME] computed from passive sampler chemistry data from 67 Great Lakes tributaries collected in 2010 and 2014 for chemicals included in the ToxCast database. _**An “X” in the embedded table indicates major land uses within the watersheds that are significantly correlated with exceedance of an EAR threshold of 0.001 for individual chemicals. Chemicals not represented in the table did not have significant correlations or were present at less than XX% of sites.**_ [Map name, references locations included on the map in Figure 1; Chemicals, number of chemicals with computed EAR values.] 

The bold-italics text depends on our decision to include correlation tables for individual chemicals.

**Comment by ldecicco-USGS** [comment]
For our last paper, embedding the figure captions *just right* was incredibly tedious. Can we do the captions via Word or Illustrator?

**Comment by srcorsi-USGS** [comment]
Can we do this with an Rmarkdown -> MSWord script? One figure per page with the caption beneath it as text?

**Comment by ldecicco-USGS** [comment]
Absolutely, I just want to hammer home I don't want to do it in the pdf version of the figure ever again.

**Comment by srcorsi-USGS** [comment]
Sounds good--we can always convert the MS Word file to pdf after the fact for the final journal submission

**Comment by srcorsi-USGS** [comment]
Decision from this morning: Figure captions should be:

Figure SI-A. (CHANGE LETTER FROM A TO D ON PAGES 1-4) Maximum exposure-activity ratios (EAR) for [ADD CHEMICAL CLASS NAMES FOR EACH PAGE] computed from passive sampler chemistry data from 69 Great Lakes tributaries collected in 2010 and 2014 for chemicals included in the ToxCast database. [Site names are followed parenthetically by the map names from Figure 1; # Chems, number of chemicals with computed EAR values; EAR<sub>chem</sub>, exposure activity ratio]

Tweak to make:
1. in x-axis, change EAR to EAR<sub>chem</sub>.

**Comment by ldecicco-USGS** [comment]
See stacked_supplement_w_captions.pdf in Supplemental
