### ISSUE TITLE
sites monitored varies

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#16]
Need to add n-sites monitored in the chem_info tab for the toxeval input file that indicates how many sites were included. Is the original colum "n_sites" a count of how many sites have detections?  I'm not sure where that comes from.

It would also be worth defining why certain sites are missing -- not necessarily for the table, but for our own info, so I have summarized what I have gathered from a bit of investigation of the original data files:

1. Chems with 25 sites: pharms that have data from 2010 for some additional pharm analysis that was not continued. I think this was some work in the early stages of pharm2 that the NWQL provided for a subset of our sites beyond the chemicals that were originally requested.

2. Pharms with 36 sites were included in the 2014 sampling period, but not the 2010 sampling period. One site was missing for pharms compared to other parameters during 2014 (St. Louis at Scanlon). 

3. Six PBDEs with 37 sites from 2014 were not analyzed in 2010.

4. 15 chems with 55 sites. Some of this is due to a change in the WW indicator schedules between 2010 and 2014: 53 WW indicators were analyzed in 2010 and 46 in 2014. The rest are pharmaceuticals that were included in 2010, but not in 2014.

5. 8 chems have between 61 and 68 sites represented. They are all from the WW indicator schedule. I can't figure out why they are not 69 which is the full 2010 + 2014 site list.

See this code to get a table with number of sites per chemical.

test_orig_chems <- 
  tox_list$chem_data %>%
  group_by(CAS) %>%
  summarise(site_count_orig = length(unique(SiteID))) %>%
  arrange(site_count_orig) 

test_orig_chems <- left_join(test_orig_chems,tox_list$chem_info)

**Comment by ldecicco-USGS** [comment]
Yeah, n_sites is number of sites with detections. I updated the script to include "sites_tested" and changed the column name to "sites_det". 

The updated file should be synced on your one drive (or you can re-run the drake data setup plan)

**Comment by ldecicco-USGS** [comment]
Got a few of the wastewater chemicals back up to 69 sites, the "update" had a slightly different way to represent estimated values than the non-update. So now I just need to figure out why 1 site is missing Thiabendazole and 2 sites are missing Diphenhydramine (Pharmaceuticals)

**Comment by ldecicco-USGS** [comment]
OK, got those up to 69 as well. Seems to be a little bug/Excel issues/🤷 related to:
https://github.com/tidyverse/readxl/issues/360

I was able to hand fix it...but something to keep in mind if numbers don't match up as we expect when a column is a mix of numbers and text (and our data is that way a lot because of <'s)
