### ISSUE TITLE
Class stack IHC

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#18]
1. Change the order of IHC1 and IHC2. IHC1 is downstream. changing IHC1 to be M15 and IHC2 to be M14 will put them in downstream order on the stacked bar chart consistent with the other three rivers that have more than one site. 

2. We will have to have Michelle change it on the map also. 

3. It will have to be changed in the table as well.

**Comment by ldecicco-USGS** [comment]
1&3 are done.

**Comment by ldecicco-USGS** [comment]
(sent an email to Michelle)

**Comment by ldecicco-USGS** [comment]
and it's updated in OneDrive
