### ISSUE TITLE
Review Drake Workflow

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#20]
Let's review the Drake workflow to get me up to date. Can we organize/document it like this:

1. Setup data
2. Define parameters for analysis (EAR > 0.001 at 10% of sites or more)
3. Generate manuscript figures and define figure numbers
4. Generate SI figures and define figure numbers
5. Generate manuscript tables and define table numbers
6. Generate SI tables and define table numbers

**Comment by ldecicco-USGS** [comment]
So running the 2 drake scripts do the "Setup data" phase, but their output now gets pushed to our shared OneDrive, so as long as I've run it...you've got the updated data.

Then:
https://github.com/ldecicco-USGS/passive_tox/blob/master/manuscript_workflow.R
That gets our final mixture script, runs the R figures (manuscript and supplemental).

I'm not 100% still what tables we plan to use. When we clearly define that, we can add it to the script

**Comment by srcorsi-USGS** [comment]
As it stands, I think that mixtures is the only table in the manuscript. Or did we decide that land use goes in the manuscript?? the land use table doesn't come from a script anyway.
