### ISSUE TITLE
Mixtures next steps

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#3]
1. Define which genes drop when going from toxcast to panther
2. Define which endpoints drop when going from toxcast to AOPs
3. Test methods with 2 sites, 5 sites, 10 sites as threshold with 0.001 EAR and 0.00001 EAR.
4. Analysis logic: Define chemicals and mixtures, then use AOPs and Kegg pathways to interpret where possible.

**Comment by ldecicco-USGS** [comment]
@srcorsi-USGS ...try this and let me know if there are errors:

1. Update toxEval:
a. Open RStudio fresh (ie..don't have toxEval loaded!)
```r
devtools::install_github("USGS-R/toxEval")
```
2. Do an upstream pull for this repo. In your Terminal:
```
git pull upstream master
```
3. Run the app:
```r
shiny::runApp("apps/Mixture_Exploration", launch.browser = TRUE)
```

I think this covers 1-3.

**Comment by srcorsi-USGS** [comment]
First attempt at devtools install failed with the normal rlang error that I have been getting whenever I try this:
![image](https://user-images.githubusercontent.com/1444781/68490165-1dbdd800-020e-11ea-8d82-07e7f9d68288.png)


I had to go to the R package directory, delete the rlang package, re-install the rlang package, update all other packages, then go back to the github installation. It asked about updating another package (sp) in that process even though I updated all before the installation attempt. Ultimately, it was installed successfully.

**Comment by srcorsi-USGS** [comment]
Comparing this "app" to the triple graph appears to give different results for individual chemicals. I think all individual chemicals should show up if they meet the criteria, correct? Test case: threshold = 0.001, site threshold = 4 (5 or more sites). I can count > 10 chemicals that meet this criteria in the triple graph, but only atrazine and caffiene show up in the Tox Mixtures app. Am I misinterpreting what should come from the Tox Mixtures app? @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
The app will look at criteria that are met by *1* endpoint...so no, you cannot compare the triple fig with this type of mixture's analysis. The triple fig is summing all the EARs for all the endpoints.

**Comment by srcorsi-USGS** [comment]
Number of chemicals on the individual tabs is sometimes incorrect. Given that issue, also should double check the number of sites and number of samples. 

**_Final table options_**
Let's talk about a final table for journal format. Might there be a way to have the final table and add the chemical mixtures? I haven't come up with a great idea to keep it manageable for a journal yet.  the final tab is great. If there is a way to include the chems, that would do it. If that is too messy, we might have to have a second table either for the manuscript or the SI. Seems like the chem mixtures belong in the main manuscript though. It also might be worthwhile somewhere to include max EAR for each of the chem mixtures per endpoint in the final table.

This is probably all worth a discussion to brainstorm the most effective presentation before spending time on it.

Thinking more about this, here is an option for the manuscript table: Add three columns to the table in the final tab. First, the classes of compounds that influence the endpoints, second, the max number of chemicals in mixtures for that endpoint, and third, the max number of sites where that endpoint is relevant. 

I think the classes will be PAHs, pesticides, flame retardants, and plasticizers from a surficial glance. For that column, we could parenthetically add the number of compounds in each class.

**Comment by srcorsi-USGS** [comment]
As soon as we feel this is final, let's send the table to Dan. He indicated that he would look to see if the AOP mapping could be updated for the endpoints/genes that are showing up.

**Comment by ldecicco-USGS** [comment]
I meant to actually mention that the number of chemicals was calculated very lazy (it's just separating by comma, so if a chemical has a comma...which some do....it'll be wrong). I think the mixtures are right, I was just trying to do a quick check with the n_chems. To do it right I'll need to add a list-column. I'll test if that makes it too slow for an app. If so, I'll just drop the n_chem column.
