### ISSUE TITLE
OP

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#5]
In the triple plot, it shows that Octylphenol has detections at 11 sites and all appear to have EAR > 0.001. In the current version of the toxeval input file, Octyphenol does not have any detections. I have not checked other chems for this type of issue, but it may be worth a look.

**Comment by ldecicco-USGS** [comment]
p-tert-Octylphenol == "140-66-9", and there seems to be 11 sites with detentions.
4-Octylphenol == "1806-26-4" has no detections, and isn't on the graph

I had mentioned once that we need to indicate which chemicals were measured by had no detections on that graph. I think we discussed it and it was too big (to include them as rows), so we were going to add it to either the supplemental or in the caption (?)
